[#25] Entity 구현
AgileHub-DQ/Backend pull request #26
Opened 2024-03-13 05:57 UTC by minsang-alt

## 📄 Summary

> ERD에 작성한 토대로 Entity를 설계하며 Schema도 같이 작성했습니다.

결과물
![image](https://github.com/AgileHub-DQ/Backend/assets/82764703/dd463116-f4de-4748-92f0-c8aa252b623b)

## 🕰️ Actual Time of Completion

> 1일

## 🙋🏻 More

- 엔티티는 모두 단방향 관계로 작성했으며 꼭 필요한 상황이 있을 때 양방향 연관관계로 수정하시면 될 것 같습니다.
- Member는 수정되기 때문에 소셜로그인 엔티티는 작성하지 않았습니다.
- 추후에 Member와 소셜 로그인 테이블에 수정이 있다면 Schema도 같이 수정해주시면 되겠습니다.
- (추후에 작성이 끝나면 ddl-auto: create -> validate로 변경 예정) 
- 작성된 테스트 코드는 Spring security 적용 시 많은 부분이 바뀌면 삭제해도 좋을 것 같습니다

2024-03-13 15:24 UTC, Enble requested changes
코드 리뷰입니다!

2024-03-13 15:24 UTC, Enble commented on src/main/java/dynamicquad/agilehub/member/domain/Invitation.java
> +package dynamicquad.agilehub.member.domain;
초대 관련 로직에 대해서는 추후 대면 회의 때 다음과 같은 내용들을 언급해보겠습니다.
- Redis를 사용하는 방안
- RDB를 사용할 경우 status에 rejected가 필요한가
- RDB를 사용할 경우 본 레코드를 계속 유지할 것인가

2024-03-13 15:24 UTC, Enble commented on src/main/java/dynamicquad/agilehub/project/domain/MemberProjectRole.java
> +package dynamicquad.agilehub.project.domain;
이건 불확실하지만 spring security 구현에 따라서 추후 role과 관련된 사항은 수정될 수 있습니다.

2024-03-13 15:24 UTC, Enble commented on src/main/java/dynamicquad/agilehub/sprint/domain/SprintStatus.java
> +    private final String description;
description 필드의 용도가 무엇인가요?

2024-03-14 00:23 UTC, minsang-alt commented on src/main/java/dynamicquad/agilehub/global/domain/BaseEntity.java
> +@NoArgsConstructor
상속받는 `Member`와 `Project`를 생성할 때 BaseEntity에 접근할 수 없어서 컴파일 에러가 생겼습니다. 대신 외부에서 접근을 막기 위해 접근제어를 protected로 바꾸고 @AllArgsConstructor를 제거하겠습니다

2024-03-14 00:40 UTC, minsang-alt commented on src/main/java/dynamicquad/agilehub/issue/domain/Comment.java
> +@AllArgsConstructor(access = AccessLevel.PRIVATE)
빌더외에 생성자를 감추기 위해 Private으로 돌렸는데 일관성을 두기위해
`@AllArgsConstructor`는 제거하고 별도의 생성자는 private으로 변경하겠습니다

2024-03-14 00:45 UTC, minsang-alt commented on src/main/java/dynamicquad/agilehub/issue/domain/Comment.java
> +@EqualsAndHashCode(onlyExplicitlyIncluded = true, callSuper = false)
상속받는게 있다면 지울때 노란줄이 그어져서 추가하긴 했습니다.
![image](https://github.com/AgileHub-DQ/Backend/assets/82764703/11751968-f58c-4b22-8841-79e8dd27ad00)

2024-03-14 00:45 UTC, minsang-alt commented on src/main/java/dynamicquad/agilehub/sprint/domain/SprintStatus.java
> +    private final String description;
그냥 헷갈릴까봐 추가적으로 명시한건데 지우겠습니다

2024-03-14 00:48 UTC, minsang-alt commented on src/main/java/dynamicquad/agilehub/issue/domain/Issue.java
> +@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
저번에 dtype 얘기 나와서 당연히 싱글테이블 전략 사용하는 줄 알았는데 다른 전략이 더 좋을까요?
일단 에픽이나 스토리나 테스크를 조회할때 같이 가져오는 상황이 많을 것 같아서 하나의 테이블에 두는 것도 괜찮을거라 생각했습니다

2024-03-14 00:49 UTC, minsang-alt commented on src/main/java/dynamicquad/agilehub/member/domain/Invitation.java
> +package dynamicquad.agilehub.member.domain;
초대관련은 redis를 사용하면 좋을것같습니다. 👍

2024-03-14 02:01 UTC, Enble commented on src/main/java/dynamicquad/agilehub/issue/domain/Comment.java
> +@EqualsAndHashCode(onlyExplicitlyIncluded = true, callSuper = false)
의도적인 설계임을 인정하는 의미에서 유지해도 좋은 것 같습니다.

2024-03-14 02:04 UTC, Enble commented on src/main/java/dynamicquad/agilehub/issue/domain/Issue.java
> +@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
저는 기초 설계 단계에서부터 비정규화하는게 그렇게 좋지 않을 것이라고 생각했고, 자식 타입의 null 허용 문제 등의 이슈를 감수하면서까지 싱글 테이블 전략을 채택할 이유를 찾지 못했습니다. 추후에 성능 이슈가 생겼을 때 비정규화를 수행해도 크게 문제될 일이 없어 보이는데 어떻게 생각하시나요?

2024-03-14 05:22 UTC, Enble approved these changes
LGTM 👍

2024-03-14 05:22 UTC, merged